name: Build And Run Tests

on: 
  push:
  workflow_dispatch:
    inputs:
      actor:
        description: 'The actor that kicked off the workflow'
        required: true
        type: string
      
      repository:
        description: 'The name of the source repository'
        required: true
        type: string

      message:
        description: 'Message to display as part of the run name'
        required: true
        type: string

jobs:
    Build-And-Test:
        runs-on: windows-latest
        steps:

            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Setup CMake
              uses: threeal/cmake-action@v1.3.0

            - name: Build the project
              run: cmake --build build

            - name: Test
              run: ctest --test-dir build -C Debug --output-on-failure

run-name: >-
  ${{ ( github.event_name == 'push' && format('{0}: {1}', github.actor, github.event.head_commit.message) ) || 
      ( github.event_name == 'workflow_dispatch' && format('{0}: Dispatched from {1} with message: {1}', github.event.inputs.actor, github.event.inputs.repository, github.event.inputs.message) )}}
            
