name: Build-And-Run-Tests

on: 
  push:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to display as part of the run name'
        required: true
        type: string

jobs:
    Build-And-Test:
        runs-on: windows-latest
        steps:

            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Setup CMake
              uses: threeal/cmake-action@v1.3.0

            - name: Build the project
              run: cmake --build build

            - name: Test
              run: ctest --test-dir build -C Debug --output-on-failure

run-name: "${{github.actor}}: ${{github.event.head_commit.message || format('Dispatched from {0} with message: {1}', github.event.repository.name, github.event.inputs.message)}}"
            
