name: Build And Run Tests

on: 
  push:
  workflow_dispatch:
    inputs:
      actor:
        description: 'The actor that kicked off the workflow'
        required: true
        type: string
      
      repository:
        description: 'The name of the source repository'
        required: true
        type: string

      message:
        description: 'Message to display as part of the run name'
        required: true
        type: string

jobs:
    Build-And-Test:
        runs-on: windows-latest
        steps:

            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Install Ninja
              uses: seanmiddleditch/gha-setup-ninja@master

            - name: setup devcmd
              uses: ilammy/msvc-dev-cmd@v1.13.0

            - name: Build everything and run all Tests"
              run: cmake --workflow --preset NinjaBuildAndTest

run-name: >-
  ${{ ( github.event_name == 'push' && format('{0}: {1}', github.actor, github.event.head_commit.message) ) || 
      ( github.event_name == 'workflow_dispatch' && format('{0}: Dispatched from {1} with message: {2}', github.event.inputs.actor, github.event.inputs.repository, github.event.inputs.message) )}}
            
